"""Add AssignmentAnalytics table

Revision ID: a5f370661390
Revises: 89061f66c74a
Create Date: 2025-12-22 01:53:10.858861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5f370661390'
down_revision: Union[str, None] = '89061f66c74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('total_submissions', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('max_score_achieved', sa.Float(), nullable=True),
    sa.Column('min_score_achieved', sa.Float(), nullable=True),
    sa.Column('ai_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_analytics')
    # ### end Alembic commands ###
